## Clock signal
##Bank = 35, Pin name = IO_L12P_T1_MRCC_35,					Sch name = CLK100MHZ
set_property PACKAGE_PIN E3 [get_ports clk]						
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports {A[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pout[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pout[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {select[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {select[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {select[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {select[0]}]

set_property PACKAGE_PIN U8 [get_ports {A[3]}]
set_property PACKAGE_PIN U9 [get_ports {A[2]}]
set_property PACKAGE_PIN R7 [get_ports {A[1]}]
set_property PACKAGE_PIN R6 [get_ports {A[0]}]
set_property PACKAGE_PIN R5 [get_ports {B[3]}]
set_property PACKAGE_PIN V7 [get_ports {B[2]}]
set_property PACKAGE_PIN V6 [get_ports {B[1]}]
set_property PACKAGE_PIN V5 [get_ports {B[0]}]
set_property PACKAGE_PIN T8 [get_ports {pout[3]}]
set_property PACKAGE_PIN V9 [get_ports {pout[2]}]
set_property PACKAGE_PIN R8 [get_ports {pout[1]}]
set_property PACKAGE_PIN T6 [get_ports {pout[0]}]
set_property PACKAGE_PIN T1 [get_ports {select[3]}]
set_property PACKAGE_PIN R3 [get_ports {select[2]}]
set_property PACKAGE_PIN P3 [get_ports {select[1]}]
set_property PACKAGE_PIN P4 [get_ports {select[0]}]
set_property PACKAGE_PIN V2 [get_ports flagin]

set_property IOSTANDARD LVCMOS33 [get_ports flagin]
create_clock -period 10.000 -name clk -waveform {0.000 5.000}